### ISSUE TITLE
Support volume property

### ISSUE THREAD

**Issue by k-u-s** [StefH/Howler.Blazor#17]
I would like to propose exposing
https://github.com/goldfire/howler.js#volume-number-10 
in
src/Howler.Blazor/Components/HowlOptions.cs 
as double? in order to have better control on how multiple sounds are played.

**Comment by grierson** [comment]
Is possible to update the volume once it's playing?

`public ValueTask Volume(int soundId, double volume)  {  
    return _runtime.InvokeVoidAsync("howl.volume", soundId, volume); 
}`

**Comment by StefH** [comment]
@grierson 
This can be added.

And also there should be a global / static Volume set option, which sets the volume for all sounds.
```
// Change global volume.
Howler.volume(0.5);
```

Can you create a PR?

**Comment by StefH** [comment]
https://github.com/StefH/Howler.Blazor/pull/24
