### ISSUE TITLE
Is there a way to make it work with Data URI?

### ISSUE THREAD

**Issue by thepra** [StefH/Howler.Blazor#21]
I'm storing the audio files locally in the client with indexeddb as base64 string but I can't figure out how to feed in the Howl the audio data, what I use to make it ingest such data correctly?

**Comment by StefH** [comment]
See
https://github.com/StefH/Howler.Blazor/blob/master/examples/Howler.Blazor-AudioPlayer/Pages/Example.razor

**Comment by thepra** [comment]
I don't see where a blob of base64 string or even byte[] is being used

**Comment by StefH** [comment]
You can just pass a base64 string or byte[] to `Play(...)`
