### ISSUE TITLE
Change playback rate

### ISSUE THREAD

**Issue by chris1411** [StefH/Howler.Blazor#6]
Thanks for creating this wrapper. Its super easy to use. Any plans on implemented the howler rate method for changing the playback rate? I can submit a PR for it but didn't want to duplicate work in case you already had plans for it. 

Also, I created a reusable audio player component out of your example that includes a progress bar and timer. I can do a PR for that as well if you like.

**Comment by StefH** [comment]
Glad you like it.

For the playback-rate, you can create a PR.

I already build a player like here with progress bar and timer:
- https://github.com/StefH/WebDAV-AudioPlayer/tree/master/src/Blazor-WebDAV-AudioPlayer.v2
![image](https://user-images.githubusercontent.com/249938/81141986-8e9c3d80-8f6e-11ea-941e-ccc4a16ddfa0.png)

However, if your component is very common, maybe we can include this in a new package?

**Comment by StefH** [comment]
https://github.com/StefH/Howler.Blazor/pull/7
